### PR TITLE
fix CrossValidationStorage initialisation

### LINKED ISSUE #4848: MacOS MKL undefined behaviour
Right now there is undefined behaviour when running the tests. It's probably a coincidence that this only happens in MacOS test. What is probably happening is that a class member somewhere in `CrossValidationFoldStorage`, or it's base classes, is not being initialised and the comparison between two instances fails. To find the bug either look manually for what's wrong or use a sanitizer, or even a good IDE.

This error can be seen in Azure pipelines:
`/Users/runner/runners/2.165.0/work/1/s/tests/unit/base/SGObjectAll_unittest.cc:86: CrossValidationFoldStorage`

### PR DESCRIPTION
**Pull request by gf712**
This should fix #4848

### CODE REVIEW

File: src/shogun/evaluation/CrossValidationStorage.cpp [hunk 1]
```diff
@@ -75,9 +69,7 @@ CrossValidationFoldStorage::CrossValidationFoldStorage() : EvaluationResult()
 	    ParameterProperties::HYPER);
 }
 
-CrossValidationFoldStorage::~CrossValidationFoldStorage()
-{
-}
+CrossValidationFoldStorage::~CrossValidationFoldStorage() = default;
```
Comment (gf712) [inline src/shogun/evaluation/CrossValidationStorage.cpp:72]: clang-tidy suggests using default here
