### PR TITLE
fix issue: remove mktemp warnings in unit tests and libshogun example…

### LINKED ISSUE #2750: remove mktemp warnings in unit tests and libshogun examples
```CMakeFiles/streaming_onlineliblinear_sparse.dir/streaming_onlineliblinear_sparse.cpp.o: In function `main':
/home/heiko/git/shogun/shogun_develop/shogun/examples/undocumented/libshogun/streaming_onlineliblinear_sparse.cpp:35: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'```

when building the examples and unit tests

### PR DESCRIPTION
**Pull request by cdawei**
fix #2750

### CODE REVIEW

File: examples/undocumented/libshogun/base_load_all_file_parameters.cpp [hunk 1]
```diff
@@ -155,7 +155,9 @@ class CTestClassFloat : public CSGObject
 void test_load_file_parameter()
 {
 	char filename_tmp[] = "load_all_file_test.XXXXXX";
-	char* filename=mktemp(filename_tmp);
+    int fd = mkstemp(filename_tmp);
```
Comment (lisitsyn) [inline examples/undocumented/libshogun/base_load_all_file_parameters.cpp]: Could you fix indentation? Looks wrong

**Comment by lisitsyn** [comment]
Thanks! Just one small issue - according to the doc, `mkstemp` returns valid file descriptor so the file stays opened. It would be better if we close it immediately once file is created

**Comment by lisitsyn** [comment]
Ok its good to merge.

Can be later improved with some separate function.

**Comment by lisitsyn** [comment]
Travis errors looks unrelated
